[package]
name = "imagene"
version = "0.1.0"
authors = ["Simon <simon.larsson-general@protonmail.com>"]
edition = "2018"

[dependencies]
image = "0.24.9"
colored = "*"
imageproc = "0.23.0"
rusttype = "0.9.2"
